require "gosu"
require_relative "window"
require_relative "brick"
require_relative "wall"
require_relative "tank"
require_relative "enemy_tank"
require_relative "enemy_team"
require_relative "player"
require_relative "cannon"
GameWindow.new.show